FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11
COPY . /usr/src/app

WORKDIR /usr/src/app
ENV PYTHONPATH=${PYTHONPATH}:${PWD} 


RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

 
#CMD ["uvicorn","api:app","--host","0.0.0.0","--port","80","--reload"]
CMD ["uvicorn","api:app", "--host", "0.0.0.0", "--port", "80"]