FROM python:3
COPY . /usr/src/app

WORKDIR /usr/src/app
ENV PYTHONPATH=${PYTHONPATH}:${PWD} 

RUN ls
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install  --no-dev
 
 
 

CMD ["python3","main.py"]